// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern void pl_axi_dma_controller (volatile int* AXI_DMA_SLAVE, volatile unsigned int startAddress, volatile bool write, volatile int length, volatile int iterations, volatile bool enabled, volatile bool* reset_scanner, volatile int* dma_control, volatile int* dma_status, volatile int* dma_address, volatile ap_uint<1>* fabric_interupt_finished, volatile ap_uint<1>* controller_finished);

